import { readFileSync } from "fs";
import { getRootDirectory } from "./file.utils";

function getQuery(queryName: string): string {
	let queryFile = `${getRootDirectory()}/src/scripts/queries/${queryName}.sql`;
	return readFileSync(queryFile, "utf8");
}

export default {
	adminDashboard: getQuery("admin.dashboard"),
	authUser: getQuery(`user.auth`),
	saveOtp: getQuery(`auth.otp.save`),
	fetchOtp: getQuery(`auth.otp.fetch`),
	removeOtp: getQuery(`auth.otp.remove`),
	getUser: getQuery(`user.fetch`),
	saveCredentials: getQuery(`user.credentials.reset`),
	markActive: getQuery(`auth.set.active.status`),
	insertProvider: getQuery(`provider.add`),
	fetchProvider: getQuery(`provider.fetch`),
	patchProvider: getQuery(`provider.patch`),
	filterProvider: getQuery(`provider.filter`),
	updateProvider: getQuery(`provider.update`),
	addProviderContract: getQuery(`provider.contract.add`),
	providerCountReport: getQuery(`provider.count.report`),
	insertCustomer: getQuery(`customer.add`),
	insertCustomerLocation: getQuery(`customer.location.add`),
	saveCustomerSubscription: getQuery(`customer.subscription.save`),
	fetchCustomerLocation: getQuery(`customer.location.fetch`),
	insertCustomerMedicalDirector: getQuery(`customer.medical.director.add`),
	fetchCustomerMedicalDirector: getQuery(`customer.medical.director.fetch`),
	fetchCustomer: getQuery(`customer.fetch`),
	filterCustomer: getQuery(`customer.filter`),
	patchCustomer: getQuery(`customer.patch`),
	updateCustomer: getQuery(`customer.update`),
	customerCountReport: getQuery(`customer.count.report`),
	addCustomerContract: getQuery(`customer.contract.add`),
	saveCustomerTreatment: getQuery(`customer.treatments.save`),
	fetchCustomerTreatment: getQuery(`customer.treatments.fetch`),
	fetchSystemParameters: getQuery(`system.parameters.fetch`),
	insertDirector: getQuery(`director.add`),
	fetchDirector: getQuery(`director.fetch`),
	filterDirector: getQuery(`director.filter`),
	patchDirector: getQuery(`director.patch`),
	addCategory: getQuery(`category.add`),
	updateCategory: getQuery(`category.update`),
	fetchCategory: getQuery(`category.fetch`),
	addTreatment: getQuery(`treatment.add`),
	updateTreatment: getQuery(`treatment.update`),
	fetchTreatment: getQuery(`treatment.fetch`),
	addPatient: getQuery(`patient.add`),
	addQuestion: getQuery(`question.add`),
	updateQuestion: getQuery(`question.update`),
	saveQuestionTreament: getQuery(`question.treament.save`),
	fetchQuestion: getQuery(`question.fetch`),
	filterQuestions: getQuery(`question.filter`),
	savePatientMedicalHistory: getQuery(`patient.medicalhistory.save`),
	fetchPatientMedicalHistory: getQuery(`patient.medicalhistory.fetch`),
	updatePatient: getQuery(`patient.update`),
	fetchPatient: getQuery(`patient.fetch`),
	filterPatient: getQuery(`patient.filter`),
	addGfe: getQuery(`gfe.add`),
	addGfeTreatment: getQuery(`gfe.treatment.add`),
	fetchGfeTreatment: getQuery(`gfe.treatment.fetch`),
	saveProviderCommentOnGfe: getQuery(`gfe.provider.comment.save`),
	saveGfeReview: getQuery("gfe.mark.review"),
	saveGfeViewed: getQuery("gfe.view.add"),
	fetchGfe: getQuery(`gfe.fetch`),
	filterGfe: getQuery(`gfe.filter`),
	queuedGfe: getQuery(`gfe.queued.fetch`),
	getGfeByIds: getQuery(`gfe.fetch.ids`),
	getGfeById: getQuery(`gfe.fetch.id`),
	gfeMarkStatus: getQuery(`gfe.mark.status`),
	gfeMarkTreatmentStatus: getQuery(`gfe.treatment.mark`),
	gfeAddAnswers: getQuery(`gfe.question.add`),
	gfeQuestionFetch: getQuery(`gfe.question.fetch`),
	gfeSetBooking: getQuery(`gfe.set.booking`),
	gfeCountReport: getQuery(`gfe.count.report`),
	gfeDashboard: getQuery(`gfe.dashboard`),
	addLocation: getQuery(`location.add`),
	updateLocation: getQuery(`location.update`),
	fetchLocation: getQuery(`location.fetch`),
	filterLocation: getQuery(`location.filter`),
	deleteLocation: getQuery(`location.remove`),
	addManufacture: getQuery(`manufacture.add`),
	updateManufacture: getQuery(`manufacture.update`),
	fetchManufacture: getQuery(`manufacture.fetch`),
	removeManufacture: getQuery(`manufacture.remove`),
	addCompliance: getQuery(`compliance.add`),
	updateCompliance: getQuery(`compliance.update`),
	fetchCompliance: getQuery(`compliance.fetch`),
	removeCompliance: getQuery(`compliance.remove`),
	getInvoiceToBeGenerated: getQuery(`invoices.to.be.generated`),
	addInvoice: getQuery(`invoice.add`),
	patchInvoice: getQuery(`invoice.patch`),
	addInvoiceDetail: getQuery(`invoice.detail.add`),
	fetchInvoice: getQuery(`invoice.fetch`),
	filterInvoice: getQuery(`invoice.filter`),
	fetchInvoiceDetail: getQuery(`invoice.details.fetch`),
	addPayment: getQuery(`payment.add`),
	fetchPayment: getQuery(`payment.fetch`),
	filterPayment: getQuery(`payment.filter`),
	updatePayment: getQuery(`payment.update`),
	addAdvertisement: getQuery(`advertisement.add`),
	fetchAdvertisement: getQuery(`advertisement.fetch`),
	updateAdvertisement: getQuery(`advertisement.update`),
	fetchAdvertisementByCustomer: getQuery(`advertisement.fetch.by.customer`),
};
